exp_dir: /content/drive/MyDrive/10708_exp/VT
exp_name: MVT-zipper
repeat_id: 0
comment: test
log_level: INFO
run_id: 1
seed: 1234

model:
  name: VT_AE_Detector
  load_model: !!bool True
  load_path: "/content/drive/MyDrive/10708_exp/VT/MVT-zipper/VT_AE_Detector_debug_Feb-23-10-27-00/models/model.pth"

logger_name: AD-logger

dataset:
  name: mvtec
  root: "/content"
  batch_size: 1
  product: zipper
  load_train: !!bool False
  load_test: !!bool True
  use_cache: !!bool False
  cache_dir: "datasets/processed"
  patch_size: 64

train:
  epochs: 5
  save_all_models: !!bool False
  lr_dacey: 0.95
  optim:
    lr: 0.0001
    betas: [ 0.9, 0.999 ]
    weight_decay: 0.0001
    amsgrad: !!bool False

