exp_dir: exp
exp_name: debug_exp
repeat_id: 0
comment: debug
log_level: INFO
run_id: 1
seed: 1234

model:
  name: VT_AE_Detector

logger_name: AD-logger

dataset:
  name: mvtec
  root: "/content"
  batch_size: 8
  product: bottle
  load_test: !!bool False
  use_cache: !!bool False
  cache_dir: "datasets/processed"

train:
  epochs: 5
  save_all_models: !!bool False
  lr_dacey: 0.95
  optim:
    lr: 0.0001
    betas: [ 0.9, 0.999 ]
    weight_decay: 0.0001
    amsgrad: !!bool False

