exp_dir: /content/drive/MyDrive/10708_exp/VT
exp_name: MVT-zipper
repeat_id: 0
comment: debug
log_level: INFO
run_id: 1
seed: 1234

model:
  name: VT_AE_Detector

logger_name: AD-logger

dataset:
  name: mvtec
  root: "/content"
  batch_size: 8
  product: zipper
  load_train: !!bool True
  load_test: !!bool False
  use_cache: !!bool False
  cache_dir: "datasets/processed"

train:
  epochs: 400
  save_all_models: !!bool False
  lr_dacey: 0.95
  optim:
    lr: 0.0001
    betas: [ 0.9, 0.999 ]
    weight_decay: 0.0001
    amsgrad: !!bool False

